name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Check if tests exist
      run: |
        if [ ! -d "__tests__" ] && [ ! -d "test" ]; then
          echo "No tests found, skipping test execution."
          exit 0
        fi

    - name: Run tests
      run: npm test
